name: "Cancer Biology Lab @ BITS Pilani"
description: "This is the official web page for the Cancer Biology Lab at BITS Pilani."

url: "http://cancerlab.github.io"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown

future: true
